Changed README to suggest requiring em-http-request
```ruby
require 'em-http-request'
```

I orginally forgot to do this and got the predictable error:
Keen IO Exception: An EventMachine loop must be running to use
publish_async calls (Keen::Error)

I got this error even though the code had:
```ruby
Thread.new { EventMachine.run }
```
The problem was that the error message related to missing EventMachine:
  NameError: uninitialized constant EventMachine

was being swallowed in the Thread.new call so it took me a little longer
than it should have to realize that I never required EventMachine or em-http-request.